name: Publish Packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@vietvho'
          cache: 'npm'

      - run: npm install   # 👈 workspace linking happens here
      - run: npm i --save-dev @types/node
        working-directory: "./types"

      - run: npm run build -w @vietvho/lumea-types
      - run: npm publish
        if: github.event_name == 'push'
        working-directory: ./types
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm run build -w @vietvho/lumea-db
      - run: npm publish
        if: github.event_name == 'push'
        working-directory: ./db
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
