name: Publish Packages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - run: npm install

      # --- TYPES FIRST ---
      - run: npm run build
        working-directory: ./types

      - run: npm publish
        working-directory: ./types
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # --- DB AFTER ---
      - run: npm run build
        working-directory: ./db

      - run: npm publish
        working-directory: ./db
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
